version: "3"

services:
  frontend:
    depends_on:
     - backend
    build: ./frontend
    container_name: finance_tracker_frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000

  backend:
    depends_on:
      - postgres
    build: ./backend
    container_name: finance_tracker_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_HOST
      - DATABASE_PORT
      - DATABASE_NAME
      - DATABASE_USER
      - DATABASE_PASSWORD
    command: pipenv run uvicorn app.api.routes:app --host 0.0.0.0 --port 8000 --reload
  postgres:
    image: postgres:16-alpine
    container_name: finance_tracker_db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
