version: "3"

services:
  frontend:
    depends_on:
     - backend
    build: ./frontend
    container_name: finance_tracker_frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000
      - CHOKIDAR_USEPOLLING=true

  backend:
    depends_on:
      - postgres
    build: ./backend
    container_name: finance_tracker_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=finance_tracker
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
    command: pipenv run uvicorn app.api.routes:app --host 0.0.0.0 --port 8000 --reload
  postgres:
    image: postgres:16-alpine
    container_name: finance_tracker_db
    environment:
      POSTGRES_DB: finance_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
