version: "3"

services:
  backend:
    depends_on:
      - postgres
    build: ./backend
    container_name: finance_tracker_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/finance_tracker
    command: pipenv run uvicorn app.main:app --host 0.0.0.0 --port 8000
  postgres:
    image: postgres:16-alpine
    container_name: finance_tracker_db
    environment:
      POSTGRES_DB: finance_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
