version: "3"

tasks:
  db:console:
    desc: Open database console
    cmds:
      - docker compose exec postgres psql finance_tracker postgres

  console:
    desc: Open developement console
    cmds:
      - docker compose run --rm backend sh

  start:
    desc: Start development server (using real backend)
    cmds:
      - docker compose up
  db:init:
    desc: Initialize development environment
    cmds:
      - docker compose run --rm backend task migrate