version: "3"

tasks:
  default:
    desc: "Run all the dev tools at once"
    cmds:
      - task: format
      - task: lint
      - task: typing
      - task: test
  format:
    desc: Run formatter
    cmds:
      - ruff format
  lint:
    desc: Run linter
    cmds:
      - ruff check --fix
  typing:
    desc: Run mypy for type hints check
    cmds:
      - mypy app --strict
  migrate:
    desc: Run database migrations
    cmds:
      - alembic upgrade head
  test:
    desc: Run tests
    cmds:
      - python -m pytest {{ if .CLI_ARGS }}{{ .CLI_ARGS }}{{ else }}tests/{{ end }} 
  seed:
    desc: Seed database with initial data
    cmds:
      - python -m scripts.db_seed