name: CI checks

on: push

jobs:
  build:
    name: Setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker Compose Build
        run: docker compose -f docker-compose.yml build

  backend-checks:
    name: Backend checks
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Format
        run: docker compose -f docker-compose.yml run --rm backend task ci:format

      - name: Lint
        run: docker compose -f docker-compose.yml run --rm backend task ci:lint
