name: CI checks

on: push

jobs:
  build:
    name: Setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker Compose Build
        run: docker compose -f docker-compose.yml build
